name: Test application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java SDK 17
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 17
          distribution: temurin
      - name: Gradle test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
